FROM golang:1.15 as builder
LABEL maintainer="tomasz.szymanski@greenit.com.pl"
WORKDIR /code/
COPY code/app.go .

# budujemy aplikacje
RUN CGO_ENABLED=0 GOOS=linux go build -v -a -tags netgo -ldflags '-w' -o app .

FROM scratch
LABEL example="multi-stage"
COPY --from=builder /code/app .
CMD ["/app"]

